# Generated by Django 3.0.3 on 2020-09-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewName', models.TextField(max_length=159)),
                ('timeDate', models.DateTimeField(blank=True)),
                ('denorture', models.TextField(max_length=159, null=True)),
                ('arrival', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=159)),
                ('headman', models.TextField(max_length=159, null=True)),
                ('operator', models.TextField(max_length=159, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=159, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=159)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.TextField(max_length=159)),
                ('firstName', models.TextField(max_length=159)),
                ('secondName', models.TextField(max_length=159)),
                ('surname', models.TextField(max_length=159)),
                ('position', models.TextField(max_length=159)),
                ('callsign', models.TextField(max_length=159)),
                ('car', models.BooleanField(max_length=159, null=True)),
                ('walhie_talking', models.TextField(max_length=159, null=True)),
                ('lamp', models.IntegerField(null=True)),
                ('outlit', models.TextField(max_length=159, null=True)),
                ('telNumber', models.TextField(max_length=159)),
                ('photo', models.ImageField(height_field=100, null=True, upload_to='', width_field=100)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Crew')),
                ('education', models.ManyToManyField(to='db.Education')),
                ('searchSquad', models.ManyToManyField(to='db.SearchSquad')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_hisrory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentId', models.TextField(max_length=159)),
                ('timeDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(max_length=159)),
                ('event', models.TextField(max_length=159)),
                ('crew', models.ManyToManyField(to='db.Crew')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Volunteers')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.TextField(max_length=159)),
                ('serName', models.TextField(max_length=159)),
                ('description', models.TextField(max_length=159, null=True)),
                ('photo', models.ImageField(height_field=100, null=True, upload_to='', width_field=100)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Volunteers')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Event'),
        ),
    ]
