# Generated by Django 3.0.3 on 2020-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='age',
            field=models.TextField(default=1, max_length=159),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='car',
            field=models.TextField(max_length=159, null=True),
        ),
    ]
