# Generated by Django 3.0.3 on 2020-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20200929_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='lamp',
            field=models.TextField(max_length=159, null=True),
        ),
    ]
