# Generated by Django 3.0.3 on 2020-09-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200929_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteers',
            old_name='outlit',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='volunteers',
            old_name='walhie_talking',
            new_name='walk',
        ),
        migrations.RemoveField(
            model_name='volunteers',
            name='surname',
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='squad',
            field=models.TextField(max_length=159, null=True),
        ),
    ]
