# Generated by Django 3.0.3 on 2020-09-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20200929_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='car',
            field=models.TextField(blank=True, max_length=159, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='crew',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db.Crew'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='description',
            field=models.TextField(blank=True, max_length=159, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='education',
            field=models.ManyToManyField(blank=True, to='db.Education'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='lamp',
            field=models.TextField(blank=True, max_length=159, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='searchSquad',
            field=models.ManyToManyField(blank=True, to='db.SearchSquad'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='squad',
            field=models.TextField(blank=True, max_length=159, null=True),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='telNumber',
            field=models.TextField(blank=True, max_length=159),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='walk',
            field=models.TextField(blank=True, max_length=159, null=True),
        ),
    ]
