# Generated by Django 3.0.3 on 2020-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20200929_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='photo',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
