# Generated by Django 3.0.3 on 2020-09-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20200929_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='callsign',
            field=models.TextField(blank=True, max_length=159),
        ),
    ]
