# Generated by Django 3.0.3 on 2020-09-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20200929_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Crew'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='db.Education'),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='searchSquad',
            field=models.ManyToManyField(blank=True, null=True, to='db.SearchSquad'),
        ),
    ]
