# Generated by Django 3.0.3 on 2021-06-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewName', models.TextField(max_length=159)),
                ('timeDate', models.DateTimeField(blank=True)),
                ('denorture', models.TextField(max_length=159, null=True)),
                ('arrival', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.TextField(max_length=159)),
                ('serName', models.TextField(max_length=159)),
                ('description', models.TextField(max_length=159, null=True)),
                ('photo', models.ImageField(height_field=100, null=True, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=159, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Missing_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=159)),
                ('timeDate', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=159)),
                ('photo', models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=159)),
                ('secondName', models.TextField(max_length=159)),
                ('age', models.TextField(blank=True, max_length=159, null=True)),
                ('position', models.TextField(max_length=159)),
                ('callsign', models.TextField(blank=True, max_length=159)),
                ('car', models.BooleanField(blank=True, null=True)),
                ('walk', models.TextField(blank=True, max_length=159, null=True)),
                ('lamp', models.TextField(blank=True, max_length=159, null=True)),
                ('telNumber', models.TextField(blank=True, max_length=159)),
                ('description', models.TextField(blank=True, max_length=159, null=True)),
                ('photo', models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.Crew')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSquad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Found', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Event')),
                ('voluentres', models.ManyToManyField(blank=True, to='managment.Volunteers')),
            ],
        ),
        migrations.CreateModel(
            name='Found_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=159)),
                ('description', models.TextField(max_length=159)),
                ('photo', models.ImageField(blank=True, height_field=100, null=True, upload_to='', width_field=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='voluentres',
            field=models.ManyToManyField(blank=True, to='managment.Volunteers'),
        ),
        migrations.CreateModel(
            name='Equipment_hisrory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentId', models.TextField(max_length=159)),
                ('timeDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.TextField(max_length=159)),
                ('event', models.TextField(max_length=159)),
                ('crew', models.ManyToManyField(to='managment.Crew')),
                ('equipment', models.ManyToManyField(to='managment.Equipment')),
                ('voluenteers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Volunteers')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.Volunteers'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=159)),
                ('headman', models.TextField(max_length=159, null=True)),
                ('operator', models.TextField(max_length=159, null=True)),
                ('voluentres', models.ManyToManyField(blank=True, to='managment.Volunteers')),
            ],
        ),
    ]
