# Generated by Django 3.0.3 on 2021-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_auto_20210616_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, default=1, height_field=100, upload_to='', width_field=100),
            preserve_default=False,
        ),
    ]
