# Generated by Django 3.0.3 on 2021-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_auto_20210616_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_people',
            name='event',
            field=models.TextField(default=1, max_length=159),
            preserve_default=False,
        ),
    ]
